### ISSUE TITLE
Question about the transition

### ISSUE THREAD

**Issue by KoniHD** [samhubs/Loco-for-Yolo#2]
Hello,
Since YOLOv9 is out now [https://github.com/KoniHD/yolov9](url) I was interested if you could provide the code you used for relabeling. This would be very helpful instead of the just relabeled dataset on a private Google Drive link which I personally don't want to download 😁

**Comment by samhubs** [comment]
Hey Koni, sorry, I am not sure why this repo is still around, it was a test that I had worked on for a short period of time. Let me check if I can find the code. If you can tell me your requirement, I can help you with writing the code.
